### PR TITLE
Add controller tools back

### PR DESCRIPTION
**Pull request by jensfr**
- Description of the problem which is fixed/What is the use case
Downstream Red Hat builds require controller-tools to be in the go.mod so they can be cached due to network limitations. They can easily be removed accidentally with go mod tidy because they are not actually dependencies.

- What I did
go get sigs.k8s.io/controller-tools@v0.9.2
go get sigs.k8s.io/controller-tools/pkg/genall/help/pretty@v0.9.2
go get sigs.k8s.io/controller-tools/pkg/crd@v0.9.2
**Edit:** had to also do this (Greg)
go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.2

- How to verify it
go run sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./...""

- Description for the changelog

### CODE REVIEW

**Comment by cpmeadors** [comment]
I did a go mod download and then ran

go run sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."

and got

../../../../go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/cmd/controller-gen/main.go:25:2: missing go.sum entry for module providing package github.com/spf13/cobra (imported by sigs.k8s.io/controller-tools/cmd/controller-gen); to add:
	go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.2

This is from a brand new clone of sandboxed-container-operator with the PR branch checked out.  Either something changed or I missed a go get command the last time.  Not sure why we didn't see this previously.  Maybe everyone had a dirty test env.

**Comment by jensfr** [comment]
I don't see that problem, even with a fresh checkout

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @jensfr

**Comment by bpradipt** [comment]
Added a reference issue to fix it in code - https://github.com/openshift/sandboxed-containers-operator/issues/294

**Comment by gkurz** [comment]
> I did a go mod download and then ran
> 
> go run sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
> 
> and got
> 
> ../../../../go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/cmd/controller-gen/main.go:25:2: missing go.sum entry for module providing package github.com/spf13/cobra (imported by sigs.k8s.io/controller-tools/cmd/controller-gen); to add: go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.2
> 

I hit exactly the same error and if I do `go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.2` as suggested in the error then test succeeds. This `go get` command simply adds `github.com/inconshreveable/mousetrap` and `github.com/spf13/cobra` as indirect dependencies. @jensfr do you see them in your `go.mod` ?

> This is from a brand new clone of sandboxed-container-operator with the PR branch checked out. Either something changed or I missed a go get command the last time. Not sure why we didn't see this previously. Maybe everyone had a dirty test env.

**Comment by gkurz** [comment]
> Travelling back today and probably won't get to this. Feel free to send another PR to fix this

Since your PR has `Maintainers are allowed to edit this pull request.`, I could simply force-push to your branch :wink:

**Comment by jensfr** [comment]
Nice, thank you @gkurz

**Pull request merged**
