### PR TITLE
Update operator SDK instructions.

### LINKED ISSUE #263: Instructions for downloading operator SDK is outdated.
**Description**

The description in [docs](https://github.com/openshift/sandboxed-containers-operator/tree/main/docs)/DEVELOPMENT.md only downloads a empty file. Looking at the operatorSDK home page the instruction seems outdated.

**Steps to reproduce the issue:**
1. Follow instructions on page.
2. Notice the file is 0 bytes.
3. Profit

**Describe the results you received:**

0 bytes file. :-(

**Describe the results you expected:**

many bytes file. :-)

### PR DESCRIPTION
**Pull request by smuda**
**- Description of the problem which is fixed/What is the use case**

The instructions for downloading the operator SDK was updated from operator SDK home page.

Fixes #263 

**- What I did**

Updated the instructions.

**- How to verify it**

Follow the instructions. Notice that the file now is more than 0 bytes and also is an executable.

**- Description for the changelog**

Nope. I don't think this should be inserted into the changelog.

### CODE REVIEW

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @smuda

**Comment by smuda** [comment]
@bpradipt Is it possible the tests are a bit flunky? Both in this PR (where I only updated the markdown instructions) and #266 the same tests are failing.

**Comment by bpradipt** [comment]
> @bpradipt Is it possible the e2e tests are a bit flunky? Both in this PR (where I only updated the markdown instructions) and #266 the same tests are failing.
> 
> Where are the e2e tests defined? I can't seem to find them in the repo and there is no information i [DEVELOPMENT.md](https://github.com/openshift/sandboxed-containers-operator/blob/main/docs/DEVELOPMENT.md)

@smuda yeah the tests are broken. The tests are here - https://github.com/openshift/release/tree/master/ci-operator/jobs/kata-containers

**Review by littlejawa — APPROVED** [review]
lgtm
Thanks @smuda

**Pull request merged**
