### PR TITLE
Merge to main for 1.5

### PR DESCRIPTION
**Pull request by gkurz**
**- Description of the problem which is fixed/What is the use case**

This brings fixes for :

- https://issues.redhat.com/browse/KATA-2519
- https://issues.redhat.com/browse/KATA-2572

**- What I did**

**- How to verify it**

**- Description for the changelog**

#360
#361
#362

### CODE REVIEW

**Review by littlejawa — APPROVED** [review]
/lgtm

**Comment by snir911** [comment]
Thanks @gkurz ! LGTM

**Review by snir911 — APPROVED** [review]

**Review by beraldoleal — APPROVED** [review]
lgtm, thanks.

**Pull request merged**
