### PR TITLE
Bump to 1.8.1

### PR DESCRIPTION
**Pull request by gkurz**
This is _slighly_ improving the OSC version bump workflow and puts it in practice to prepare the release of OSC 1.8.1.

### CODE REVIEW

**Review by beraldoleal — APPROVED** [review]
lgtm, thanks.

**Review by littlejawa — APPROVED** [review]
lgtm
Thanks @gkurz !

**Comment by gkurz** [comment]
Fixes: https://issues.redhat.com/browse/KATA-3488

**Comment by gkurz** [comment]
`ci/prow/sandboxed-containers-operator-e2e` failure is expected (see https://github.com/openshift/release/pull/59339#issuecomment-2507814251 for details).

**Pull request merged**
