### PR TITLE
peerpod-ctrl: bump to fix dangling VMs

### PR DESCRIPTION
**Pull request by snir911**
Build:
```
quay.io/snir/osc-operator:9.9.2519
quay.io/snir/osc-operator-bundle:v9.9.2519
quay.io/snir/osc-operator-catalog:v9.9.2519
```

### CODE REVIEW

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @snir911

**Comment by snir911** [comment]
putting on hold, let's wait for pre-merge testing, cc @tbuskey

**Review by gkurz — APPROVED** [review]
LGTM. Thanks @snir911 !

Just a small nit : the e9406d21bc7dbe303e733f2c80d860ed52a5e944 SHA1 mentioned in the commit message belongs to CAA. IMHO it would be better to provide the full URL https://github.com/confidential-containers/cloud-api-adaptor/commit/e9406d21bc7dbe303e733f2c80d860ed52a5e944 instead.

**Comment by gkurz** [comment]
/lgtm
Thanks for the fix in the commit log @snir911 !

**Comment by tbuskey** [comment]
Working on it

**Review by littlejawa — APPROVED** [review]
lgtm
Thanks @snir911

**Comment by gkurz** [comment]
> Failing to install kataconfig on 2 clusters Logs in https://issues.redhat.com/browse/KATA-2519

Node is degraded because of :
```
                      - name: SANDBOXED_CONTAINERS_EXTENSION
                        value: kata-containers
```

@snir911 can you please re-push another build with this set to `sandboxed-containers` ?

**Comment by tbuskey** [comment]
premerge pass
/lgtm

**Pull request merged**
