### PR TITLE
Patch series to update Golang version and fix bundle creation for dev

### PR DESCRIPTION
**Pull request by bpradipt**
**- Description of the problem which is fixed/What is the use case**
Build and deploy of operator bundle from sources fails

**- What I did**
Fixed the image name, added dev instructions and bumped up Golang

**- How to verify it**
Instructions to build and deploy operator by following the [guide](docs/DOCUMENTATION.md) should work

**- Description for the changelog**

- Update Golang version and fix bundle creation for dev

### CODE REVIEW

**Comment by bpradipt** [comment]
@jensfr @pmores ptal

**Comment by bpradipt** [comment]
The issue is due to docker pull rate limit 
```
error: build error: failed to pull image: After retrying 2 times, Pull image still failed due to error: Error initializing source docker://golang:1.15: Error reading manifest 1.15 in docker.io/library/golang: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

**Comment by bpradipt** [comment]
@pmores @jensfr replaced the golang image with quay.io one to overcome the docker pull rate limit for the e2e test.

**Review by pmores — APPROVED** [review]

**Review by jensfr — APPROVED** [review]
Thank you Pradipta!

**Comment by bpradipt** [comment]
This is no longer needed.

**Pull request closed without merging**
