### PR TITLE
Bump OSC 1.6.0

### PR DESCRIPTION
**Pull request by bpradipt**

### CODE REVIEW

**Review by gkurz — CHANGES_REQUESTED** [review]
Hi @bpradipt ! The usual workflow for a major or minor release is to merge devel into main. We try to avoid cherry-picks as much as we can because they don't coexist well with merges.

Any reason for not merging ?

I have raised the request changes flag to prevent accidental merge since the button isn't grayed out.

**Comment by bpradipt** [comment]
> Hi @bpradipt ! The usual workflow for a major or minor release is to merge devel into main. We try to avoid cherry-picks as much as we can because they don't coexist well with merges.
> 
> Any reason for not merging ?
> 
> I have raised the request changes flag to prevent accidental merge since the button isn't grayed out.

We have the cloud-credentials request feature that's not part of 1.6.0 and hence I didn't cherry-pick it. What do you suggest ?

**Comment by gkurz** [comment]
> > Hi @bpradipt ! The usual workflow for a major or minor release is to merge devel into main. We try to avoid cherry-picks as much as we can because they don't coexist well with merges.
> > Any reason for not merging ?
> > I have raised the request changes flag to prevent accidental merge since the button isn't grayed out.
> 
> We have the cloud-credentials request feature that's not part of 1.6.0 and hence I didn't cherry-pick it. What do you suggest ?

Are you referring to #376 ? If yes, what would be the impact of having this in 1.6.0 @bpradipt ?

**Comment by bpradipt** [comment]
> > > Hi @bpradipt ! The usual workflow for a major or minor release is to merge devel into main. We try to avoid cherry-picks as much as we can because they don't coexist well with merges.
> > > Any reason for not merging ?
> > > I have raised the request changes flag to prevent accidental merge since the button isn't grayed out.
> > 
> > 
> > We have the cloud-credentials request feature that's not part of 1.6.0 and hence I didn't cherry-pick it. What do you suggest ?
> 
> Are you referring to #376 ? If yes, what would be the impact of having this in 1.6.0 @bpradipt ?

Additional code will be included which we don't expect users to consume yet. Although the code will not be triggered if the  required peerpods secrets are manually created (which is what we expect the users to do for 1.6).

How about I reorder the commits when merging to main from devel so that we can select a specific commit downstream which doesn't include cloud-creds and the featuregate code. @gkurz would this be fine ?

**Comment by bpradipt** [comment]
Closing this PR as cherry-pick is to be avoided when merging from devel to main

**Pull request closed without merging**
