### PR TITLE
hide peerpods and peerpodconfigs internal objects

### PR DESCRIPTION
**Pull request by snir911**
based on:
https://docs.openshift.com/container-platform/4.12/operators/operator_sdk/osdk-generating-csvs.html#osdk-hiding-internal-objects_osdk-generating-csvs

### CODE REVIEW

**Comment by snir911** [comment]
cc @bpradipt @jensfr @pmores for reviewing

**Review by bpradipt — APPROVED** [review]
/lgtm
It's a simple change and helps with the user experience. Thanks @snir911

**Comment by tbuskey** [comment]
premerge - I don't see the PeerPod APIs.  They're invisible as they should be.

image
/lgtm

**Comment by tbuskey** [comment]
pre-merge success!  
/lgtm
/approve

**Pull request merged**
