### PR TITLE
Update go.mod dependency on machine-config

### PR DESCRIPTION
**Pull request by littlejawa**
We need to update containers/image dependency to v5.22+
As the dependency comes from machine-config, this commit brings it to
the first version that depends on containers/image 5.22

### CODE REVIEW

**Comment by littlejawa** [comment]
/cc @spotlesstofu 
I think this collides with #478, as it updates some of the same dependencies (e.g: ignition)
I'll rebase when 478 is merged

**Comment by gkurz** [comment]
Fixes: https://issues.redhat.com/browse/OCPBUGS-17456
Fixes: https://issues.redhat.com/browse/OCPBUGS-36566
Fixes: https://issues.redhat.com/browse/OCPBUGS-36567

**Comment by gkurz** [comment]
`ci/prow/sandboxed-containers-operator-e2e` failure is expected (see https://github.com/openshift/release/pull/59339#issuecomment-2507814251 for details).

**Comment by gkurz** [comment]
Fixes: https://issues.redhat.com/browse/OCPBUGS-30693

**Comment by spotlesstofu** [comment]
Fixes: https://issues.redhat.com/browse/OCPBUGS-22502
Fixes: https://issues.redhat.com/browse/OCPBUGS-22503

**Pull request merged**
