### PR TITLE
1.7 release: bump peerpod controllers to 0.9.0

### PR DESCRIPTION
**Pull request by beraldoleal**
We are still using 0.8.0-alpha, and 0.9.0 changed layout.

### CODE REVIEW

**Comment by beraldoleal** [comment]
@bpradipt @cpmeadors , revisiting the notes to prepare for the 1.7 release, I noticed we are still pointing to peerpods 0.8.

Please let me know if this PR is needed or not.

**Review by bpradipt — APPROVED** [review]
/lgtm

**Comment by bpradipt** [comment]
> @bpradipt @cpmeadors , revisiting the notes to prepare for the 1.7 release, I noticed we are still pointing to peerpods 0.8.
> 
> Please let me know if this PR is needed or not.

It's needed

**Pull request merged**
