### PR TITLE
Fix unit tests to handle webhook

### PR DESCRIPTION
**Pull request by bpradipt**
**- Description of the problem which is fixed/What is the use case**
With addition of webhook, the related unit tests need to be fixed to handle the same

**- What I did**
Updated the code to install webhook in envtest and modify the test cases

**- How to verify it**
`make test` 

**- Description for the changelog**

Fix unit tests to handle webhook

### CODE REVIEW

**Review by pmores — APPROVED** [review]
@bpradipt Great job,  thanks!  You'll have to tell me sometime a story of how you figured it out! :-)

(Nit: I'd consider making the commits cleaner by removing the parts where the first one adds some commented-out lines and the other removes them again.)

**Comment by bpradipt** [comment]
> @bpradipt Great job, thanks! You'll have to tell me sometime a story of how you figured it out! :-)
> 
> (Nit: I'd consider making the commits cleaner by removing the parts where the first one adds some commented-out lines and the other removes them again.)

Ah, I didn't realise it. Thanks for catching it. Will make changes and re-send

**Review by jensfr — APPROVED** [review]
lgtm, thank you @bpradipt

**Pull request merged**
