### PR TITLE
Update peerpodconfig-ctl dep

### PR DESCRIPTION
**Pull request by bpradipt**
Also update deps to match operator-sdk v1.28.0

Fixes: #[KATA-2271](https://issues.redhat.com//browse/KATA-2271)

### CODE REVIEW

**Review by snir911 — APPROVED** [review]
LGTM, nit, s/ctl/ctrl/ in subject

**Comment by gkurz** [comment]
> Also update deps to match operator-sdk v1.28.0

@bpradipt does this mean that operator-sdk v1.28.0 should be used to build now ?

**Comment by gkurz** [comment]
> @gkurz yes. I aligned the deps to the sdk version closest to existing deps
> 

This means we're bumping from sdk v1.26.1 to v1.28.0. The following upgrade guidelines seem to indicate that we don't need to do any other specific change :

1. https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.27.0/
2. https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.28.0/

@bpradipt can you upgrade the sdk version in `docs/DEVELOPMENT.md` as well ?

**Comment by bpradipt** [comment]
> > @gkurz yes. I aligned the deps to the sdk version closest to existing deps
> 
> This means we're bumping from sdk v1.26.1 to v1.28.0. The following upgrade guidelines seem to indicate that we don't need to do any other specific change :
> 
> 1. https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.27.0/
> 2. https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.28.0/
> 
Right.

> @bpradipt can you upgrade the sdk version in `docs/DEVELOPMENT.md` as well ?
Yes

I'll also build a catalog so that we can do a pre-merge testing.

**Review by gkurz — APPROVED** [review]
LGTM. Thanks @bpradipt !

**Review by littlejawa — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
