### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by gkurz**
Remove Cameron, add Victor and Tom.

Drop some trailing spaces on the way.

**- Description of the problem which is fixed/What is the use case**

**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Review by littlejawa — APPROVED** [review]
/lgtm
Thanks @gkurz !

**Review by bpradipt — APPROVED** [review]
/lgtm

**Comment by gkurz** [comment]
Thanks for the reviews. I'll wait for a formal ack of @vvoronko and @tbuskey before merging this.

**Pull request merged**
