### PR TITLE
Update version and change default channel

### PR DESCRIPTION
**Pull request by jensfr**
This makes two changes
1.  updates VERSION in Makefile
2. rename stable-1.3 channel to stable

### CODE REVIEW

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @jensfr

**Review by cpmeadors — APPROVED** [review]
Looks good

**Comment by jensfr** [comment]
/override ci/prow/ci-index-openshift-sandboxed-containers-operator-bundle
/overrice ci/prow/images

**Pull request merged**
