### PR TITLE
Add new annotations to CSV

### PR DESCRIPTION
**Pull request by gkurz**
**- Description of the problem which is fixed/What is the use case**

This replays #389 on devel.

**- What I did**

`git cherry-pick be8fa65d3eb77f59c794ad19cdf0c085f8dc70ca` and fixed trivial context conflict.

**- How to verify it**

- Checkout this PR
- Same change as be8fa65d3eb77f59c794ad19cdf0c085f8dc70ca

**- Description for the changelog**

Fixes: [KATA-2895](https://issues.redhat.com//browse/KATA-2895)

### CODE REVIEW

**Review by bpradipt — APPROVED** [review]
/lgtm

**Review by beraldoleal — APPROVED** [review]
LGTM, thanks.

**Review by littlejawa — APPROVED** [review]
lgtm

**Comment by gkurz** [comment]
Point to the jira for upstream.

**Pull request merged**
