### PR TITLE
Rename operator to sandboxed-containers-operator

### PR DESCRIPTION
**Pull request by bpradipt**
**- Description of the problem which is fixed/What is the use case**
Rename kata-operator to sandboxed-containers-operator
**- What I did**
Renamed kata-operator to sandboxed-containers-operator and bumped up the version to 4.8
Renamed the namespace to sandboxed-containers-operator-system
**- How to verify it**
Deploy the operator by following the instructions

**- Description for the changelog**

Rename kata-operator to sandboxed-containers-operator

### CODE REVIEW

**Comment by bpradipt** [comment]
tested on OCP 4.7 and OCP 4.8 but will be good to do few additional tests to rule out issues

**Comment by jensfr** [comment]
It looks good to me. I'm running a few tests and will approve. 

Looking at this reminded me of the question, should we also rename the CRD? It's currently called kataconfig. Should it be scconfig or something like that? Would be good to change it early before we have to support upgrades. @zanetworker ? In a new PR of course.

**Comment by zanetworker** [comment]
> Would be good to change it early before we have to support upgrades. @zanetworker ? In a new PR of course.

I think this one is debatable, and I have no strong opinion on this. On the one hand, this is a resource we expose, on the other hand,  it is descriptive of the runtime we are using. 


The questions are if we do support other runtimes, do we want to have a `SandboxedContainersConfig` and have `kata` as a field in the spec, for example: 

```yaml
apiVersion: ....
kind: SandboxedOperatorConfig
spec: 
   runtimeRef: 
       apiVersion: kata.sandboxedContainers.io
       kind: KataConfig
       name: kata-test 
   ....
```

or do we want to have different configs i.e., RuntimeOneConfig, RuntimeTwoConfig,... I tend to be in favor of the first but I have no strong opinion. @jensfr and @bpradipt WDYT?

**Review by jensfr — APPROVED** [review]
lgtm, thanks Pradipta!

**Comment by jensfr** [comment]
> or do we want to have different configs i.e., RuntimeOneConfig, RuntimeTwoConfig,... I tend to be in favor of the first but I have no strong opinion. @jensfr and @bpradipt WDYT?

I like your idea with an umbrella sandboxedcontainersconfig that contains a sub for every runtime we support, but I'll have to play with it a bit to form an opinion. Thank you!

**Comment by bpradipt** [comment]
> > Would be good to change it early before we have to support upgrades. @zanetworker ? In a new PR of course.
> 
> I think this one is debatable, and I have no strong opinion on this. On the one hand, this is a resource we expose, on the other hand, it is descriptive of the runtime we are using.
> 
> The questions are if we do support other runtimes, do we want to have a `SandboxedContainersConfig` and have `kata` as a field in the spec, for example:
> 
> ```yaml
> apiVersion: sandboxedContainers.io/v1alpha1
> kind: SandboxedContainersConfig
> spec: 
>    runtimeRef: 
>        apiVersion: kata.sandboxedContainers.io/v1alpha1
>        kind: KataConfig
>        name: kata-test 
>    ....
> ```
> 
> or do we want to have different configs i.e., RuntimeOneConfig, RuntimeTwoConfig,... I tend to be in favor of the first but I have no strong opinion. @jensfr and @bpradipt WDYT?

+1 for SandboxedContainersConfig .

**Pull request merged**
