### PR TITLE
Sync release-1.7 with devel

### PR DESCRIPTION
**Pull request by beraldoleal**
Currently release-1.7 is 14 commits behind. I'm not sure how Greg was doing before, but the discussed plan was to sync this branch and then create the alpha.1 tag. This should trigger another 1.7 downstream build.

Is there any commit that should not be included?

### CODE REVIEW

**Comment by beraldoleal** [comment]
@bpradipt @cpmeadors ^

**Review by bpradipt — APPROVED** [review]
/lgtm

**Comment by bpradipt** [comment]
@beraldoleal afaik the merge commits were not included by Greg. As for the commits, they look good. We need all of them.

**Comment by beraldoleal** [comment]
@bpradipt ok, since I created this PR directly from devel -> release-1.7 using the web interface, I can't allow remove the merges, unfortunately here. So I'm closing this one, and sending another one.

**Pull request closed without merging**
