### PR TITLE
Backports for 1.8.1

### PR DESCRIPTION
**Pull request by gkurz**
This backports fixes from the following PRs for the upcoming release of OSC 1.8.1 :
- #475
- #476
- #478
- #480
- #481

### CODE REVIEW

**Review by beraldoleal — APPROVED** [review]
LGTM, thanks

**Review by littlejawa — APPROVED** [review]
lgtm
Thanks @gkurz !

**Comment by gkurz** [comment]
CI is failing because 1.8.1 images aren't public yet.

**Pull request merged**
