### PR TITLE
a couple of follow-up changes to webhook addition

### PR DESCRIPTION
**Pull request by pmores**
This commit removes the old guard against handling duplicate KataConfig
instances from the operator code which was made obsolete by deploying
a webhook to prevent duplicates in the first place.

It also upgrades cert-manager resources versions to 'v1'.  Frankly it's
not quite clear if this change is necessary at this point, however given
both 'v1alpha2' and 'v1' work it seems that going with a released version
is reasonable and more future-proof.

**- Description of the problem which is fixed/What is the use case**

**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Review by jensfr — APPROVED** [review]
lgtm, Pavel! Thank you!

**Review by bpradipt — APPROVED** [review]
/lgtm

**Comment by bpradipt** [comment]
Re-running the e2e test to view latest artifacts

**Review by bpradipt — APPROVED** [review]
/lgtm

**Pull request merged**
